language: php
dist: trusty
install:
    composer install
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml

after_script:
  - php vendor/bin/coveralls -v
